### ISSUE TITLE
Arabic text Liguature problem

### ISSUE THREAD

**Issue by hafedh-trimeche** [delphilite/AriaNgWke#3]
Hello,
Please note that the Arabic text below is not well rendered.
Letters are not joined together.
FireFox renders well this arabic text: نص عربي
```
<!DOCTYPE HTML>
<html>
<head>
<meta charset=utf8>
<style type="text/css">
p:first-letter {
  color: red;
}
</style>
</head>
<body>
The arabic letters should apear like نص عربي
</body>
</html>
```

**Comment by delphilite** [comment]
It appears to be an issue related to Miniblink.
[https://github.com/weolar/miniblink49/issues/563](https://github.com/weolar/miniblink49/issues/563)

**Comment by hafedh-trimeche** [comment]
Hi,
I switched to this control https://github.com/salvadordf/CEF4Delphi
Based on chromium, it converts HTML to PDF functionality which I'm looking for.

Normally your project won't have any problem. Edge natively handles Arabic RTL.

Available to test this functionality.

Best regards.
